version: '3.8'

services:
  document-converter:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/input:ro
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    command: python api.py
    
  # CLI version for batch processing
  document-converter-cli:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/input:ro
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    # Override command for CLI usage
    entrypoint: ["python", "converter.py"]
    profiles: ["cli"]
