services:
  document-converter:
    image: truongginjs/ocr-converter:latest
    # Uncomment to build locally instead of using pre-built image
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/input:ro
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - OCR_LANGUAGE=eng  # Default language, can be overridden
    command: python api.py
    
  # CLI version for batch processing
  document-converter-cli:
    image: truongginjs/ocr-converter:latest
    # Uncomment to build locally instead of using pre-built image
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./data:/app/input:ro
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - OCR_LANGUAGE=eng  # Default language
    # Override command for CLI usage
    entrypoint: ["python", "converter.py"]
    profiles: ["cli"]

  # Vietnamese language specific service
  document-converter-vie:
    image: truongginjs/ocr-converter:latest
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/input:ro
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - OCR_LANGUAGE=vie  # Vietnamese language
    command: python api.py
    profiles: ["vietnamese"]
